POST http://localhost:8080/api/albums/
Content-Type: application/json
Accept: application/json

{
  "albumName": "Klaus's Album",
  "firstName": "Klaus",
  "lastName": "Unger"
}

###

POST http://localhost:8080/api/albums/
Content-Type: application/json
Accept: application/json

{
  "albumName": "new Album",
  "firstName": "Thomas",
  "lastName": "Boigner"
}

###

POST http://localhost:8080/api/albums/
Content-Type: application/json
Accept: application/json

{
  "albumName": "Joachim's album",
  "firstName": "Joachim",
  "lastName": "Grueneis"
}